name: leopard
description: Leopard game engine for Flutter. Supports Xbox Controller and XInput as well.
version: 0.0.1
repository: https://github.com/xclud/dart-gamepad
homepage: https://pwa.ir

platforms:
  web:

environment:
  sdk: ">=2.12.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  web: ^1.1.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.0
