name: gamepad
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://github.com/xclud/dart-gamepad
homepage: https://pwa.ir

environment:
  sdk: ">=2.12.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  web: ^1.1.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.0
